name: Build
on: [push]

permissions:
  actions: read
  contents: read

jobs:
  test:
    environment: build
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install node dev requirements
        run: npm install --dev
      - name: Run lint
        run: npx eslint ./js/*.js
      - name: Check configuration
        run: python test/test_config.py pt/index.json pt/scenarios.json
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.CROSS_TOKEN }}
          workflow: pipelines.yaml
          workflow_conclusion: success
          branch: main
          path: data
          repo: SchmidtDSE/plastics-pipeline
      - name: Move web CSV
        run: mv data/Pipeline\ Result/overview.csv data/web.csv
      - name: Build
        shell: bash
        run: |
          chmod +x "./sh/make.sh"
          chmod +x "./sh/npm_install.sh"
          "./sh/npm_install.sh"
          "./sh/make.sh"
      - name: Install JS deps
        shell: bash
        run: |
          chmod +x "./sh/load_deps.sh"
          "./sh/load_deps.sh"
      - name: Install browser
        shell: bash
        run: |
          chmod +x "./sh/install_browser.sh"
          "./sh/install_browser.sh"
      - name: Run unit tests
        run: grunt
  deploy:
    name: Deploy
    environment: deploy
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.CROSS_TOKEN }}
          workflow: pipelines.yaml
          workflow_conclusion: success
          branch: main
          path: data
          repo: SchmidtDSE/plastics-pipeline
      - name: Move web CSV
        run: mv data/Pipeline\ Result/overview.csv data/web.csv
      - name: Build
        shell: bash
        run: |
          chmod +x "./sh/make.sh"
          chmod +x "./sh/npm_install.sh"
          "./sh/npm_install.sh"
          "./sh/make.sh"
      - name: Install JS deps
        shell: bash
        run: |
          chmod +x "./sh/load_deps.sh"
          "./sh/load_deps.sh"
      - name: Package website
        shell: bash
        run: |
          chmod +x "./sh/package.sh"
          "./sh/package.sh"
      - name: Upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './deploy'
          remotePath: './global-plastics-tool.org'