name: Build
on: [push]

jobs:
  test:
    environment: build
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build
        shell: bash
        run: |
          chmod +x "./sh/make.sh"
          chmod +x "./sh/npm_install.sh"
          "./sh/npm_install.sh"
          "./sh/make.sh"
      - name: Install JS deps
        shell: bash
        run: |
          chmod +x "./sh/load_deps.sh"
          "./sh/load_deps.sh"
      - name: Install browser
        shell: bash
        run: |
          chmod +x "./sh/install_browser.sh"
          "./sh/install_browser.sh"
      - name: Compile with Grunt
        run: grunt