name: Build
on: [push]

jobs:
  check_language:
    environment: deploy
    runs-on: ubuntu-latest
    name: Check language
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build
        shell: bash
        run: |
          chmod +x "./sh/make.sh"
          chmod +x "./sh/npm_install.sh"
          "./sh/npm_install.sh"
          "./sh/make.sh"