jobs:
  check_language:
    environment: deploy
    runs-on: ubuntu-latest
    name: Upload static
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build
        shell: bash
        run: |
          chmod +x "./make.sh"
          chmod +x "./npm_install.sh"
          "./npm_install.sh"
          "./make.sh"
      - name: 'Check File Existence'
        uses: thebinaryfelix/check-file-existence-action@v1
        with:
          files: 'js/plastics_lang.js'