name: Deploy

on:
  workflow_run:
    workflows: 
      - build
    branches:
      - main
    types: 
      - completed

permissions:
  contents: read
  actions: read

jobs:
  
  build:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.CROSS_TOKEN }}
          workflow: sqlpipeline.yml
          workflow_conclusion: success
          branch: main
          path: data
          repo: SchmidtDSE/plastics-pipeline
      - name: Build
        shell: bash
        run: |
          chmod +x "./sh/make.sh"
          chmod +x "./sh/npm_install.sh"
          "./sh/npm_install.sh"
          "./sh/make.sh"
      - name: Install JS deps
        shell: bash
        run: |
          chmod +x "./sh/load_deps.sh"
          "./sh/load_deps.sh"
      - name: Package website
        shell: bash
        run: |
          chmod +x "./sh/package.sh"
          "./sh/package.sh"
      - name: Upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './deploy'
          remotePath: './global-plastics-tool.org'